--------------------------------------------------------
--  File created - Saturday-January-30-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BENCHMARK
--------------------------------------------------------

  CREATE TABLE "GEF2012"."BENCHMARK" 
   (	"ID" NUMBER(38,0), 
	"DATETIME" CHAR(38 BYTE), 
	"WP1" NUMBER(38,3), 
	"WP2" NUMBER(38,3), 
	"WP3" NUMBER(38,3), 
	"WP4" NUMBER(38,3), 
	"WP5" NUMBER(38,1), 
	"WP6" NUMBER(38,3), 
	"WP7" NUMBER(38,3)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BUS_COORDS
--------------------------------------------------------

  CREATE TABLE "GEF2012"."BUS_COORDS" 
   (	"NODE_NAME" VARCHAR2(35 BYTE), 
	"X_COORD" VARCHAR2(35 BYTE), 
	"Y_COORD" VARCHAR2(35 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CABLES
--------------------------------------------------------

  CREATE TABLE "GEF2012"."CABLES" 
   (	"DEVICE_NAME" VARCHAR2(50 BYTE), 
	"FROM_NODE" VARCHAR2(35 BYTE), 
	"TO_NODE" VARCHAR2(35 BYTE), 
	"LENGTH" NUMBER(10,4), 
	"CONFIG_NAME" VARCHAR2(50 BYTE), 
	"CABLE_CODE_SEQIMP" VARCHAR2(50 BYTE), 
	"CABLE_CODE_PHIMP" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CABLES_PHASE_IMPEDANCE
--------------------------------------------------------

  CREATE TABLE "GEF2012"."CABLES_PHASE_IMPEDANCE" 
   (	"CABLE_CODE_PHIMP" VARCHAR2(50 BYTE), 
	"CABLE_TYPE" VARCHAR2(35 BYTE), 
	"RA" NUMBER(10,4), 
	"RB" NUMBER(10,4), 
	"RC" NUMBER(10,4), 
	"XA" NUMBER(10,4), 
	"XB" NUMBER(10,4), 
	"XC" NUMBER(10,4), 
	"RN" NUMBER(10,4), 
	"XN" NUMBER(10,4), 
	"RAB" NUMBER(10,4), 
	"RBC" NUMBER(10,4), 
	"RCA" NUMBER(10,4), 
	"XAB" NUMBER(10,4), 
	"XBC" NUMBER(10,4), 
	"XCA" NUMBER(10,4), 
	"RMN" NUMBER(10,4), 
	"XMN" NUMBER(10,4), 
	"BA" NUMBER(10,4), 
	"BB" NUMBER(10,4), 
	"BC" NUMBER(10,4), 
	"BN" NUMBER(10,4), 
	"BM" NUMBER(10,4)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CABLES_SEQ_IMPEDANCE
--------------------------------------------------------

  CREATE TABLE "GEF2012"."CABLES_SEQ_IMPEDANCE" 
   (	"CABLE_CODE_SEQIMP" VARCHAR2(50 BYTE), 
	"CABLE_TYPE" VARCHAR2(35 BYTE), 
	"POSITIVE_SEQ_RESISTANCE" NUMBER(10,4), 
	"POSITIVE_SEQ_REACTANCE" NUMBER(10,4), 
	"ZERO_SEQ_RESISTANCE" NUMBER(10,4), 
	"ZERO_SEQ_REACTANCE" NUMBER(10,4), 
	"POSITIVE_SEQ_SUSCEPTANCE" NUMBER(10,4), 
	"ZERO_SEQ_SUSCEPTANCE" NUMBER(10,4), 
	"NORMAL_AMPACITY" NUMBER(*,0), 
	"EMERGENCY_AMPACITY" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CABLES_SPACING
--------------------------------------------------------

  CREATE TABLE "GEF2012"."CABLES_SPACING" 
   (	"SPACING_ID" VARCHAR2(50 BYTE), 
	"TYPE_DESCRIPTION" VARCHAR2(50 BYTE), 
	"D12" NUMBER(10,4), 
	"D23" NUMBER(10,4), 
	"D34" NUMBER(10,4), 
	"D13" NUMBER(10,4), 
	"D14" NUMBER(10,4)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CABLE_CONFIGS
--------------------------------------------------------

  CREATE TABLE "GEF2012"."CABLE_CONFIGS" 
   (	"CONFIG_NAME" VARCHAR2(50 BYTE), 
	"PHASE" NUMBER(*,0), 
	"PHASE_CONDUCTOR_A" VARCHAR2(35 BYTE), 
	"PHASE_CONDUCTOR_B" VARCHAR2(50 BYTE), 
	"PHASE_CONDUCTOR_C" VARCHAR2(50 BYTE), 
	"NEUTRAL_CONDUCTOR_N" VARCHAR2(50 BYTE), 
	"SPACING_NAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CABLE_TYPES
--------------------------------------------------------

  CREATE TABLE "GEF2012"."CABLE_TYPES" 
   (	"CABLE_NAME" VARCHAR2(50 BYTE), 
	"PHASE_CONDUCTOR_NAME" VARCHAR2(50 BYTE), 
	"NEUTRAL_CONDUCTOR_NAME" VARCHAR2(50 BYTE), 
	"DIAMETER_OVER_INSULATION" NUMBER(10,4), 
	"DIAMETER_OVER_SCREEN" NUMBER(10,4), 
	"OUTSIDE_DIAMETER" NUMBER(10,4), 
	"COPPER_NEUTRAL" NUMBER(10,4), 
	"JACKET_THICKNESS" NUMBER(10,4), 
	"NORMAL_AMPACITY_1" NUMBER(10,4), 
	"EMERGENCY_AMPACITY_1" NUMBER(10,4), 
	"NORMAL_AMPACITY_2" NUMBER(10,4), 
	"EMERGENCY_AMPACITY_2" NUMBER(10,4), 
	"NUMBER_OF_NEUTRAL_STRINGS" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CENTER_TAPPED_LOADS
--------------------------------------------------------

  CREATE TABLE "GEF2012"."CENTER_TAPPED_LOADS" 
   (	"LOAD_NAME" VARCHAR2(50 BYTE), 
	"XFMR_NAME" VARCHAR2(50 BYTE), 
	"MODEL_NAME" VARCHAR2(50 BYTE), 
	"PROFILE_NAME" VARCHAR2(50 BYTE), 
	"INTERVAL" NUMBER(*,0), 
	"PHASE" NUMBER(*,0), 
	"FROM_NODE" VARCHAR2(35 BYTE), 
	"RATED_VOLTAGE" NUMBER(10,4), 
	"CONNECTION" VARCHAR2(10 BYTE), 
	"KVA_RATING_LN_1" NUMBER(10,4), 
	"KVA_RATING_LN_2" NUMBER(10,4), 
	"KVA_RATING_LL" NUMBER(10,4), 
	"USAGE_FACTOR_LN_1" NUMBER(10,4), 
	"USAGE_FACTOR_LN_2" NUMBER(10,4), 
	"USAGE_FACTOR_LL" NUMBER(10,4), 
	"POWER_FACTOR_LN_1" NUMBER(10,4), 
	"POWER_FACTOR_LN_2" NUMBER(10,4), 
	"POWER_FACTOR_LL" NUMBER(10,4), 
	"PHASE_LN_1_KW" NUMBER(10,4), 
	"PHASE_LN_1_KVAR" NUMBER(10,4), 
	"PHASE_LN_2_KW" NUMBER(10,4), 
	"PHASE_LN_2_KVAR" NUMBER(10,4), 
	"PHASE_LL_KW" NUMBER(10,4), 
	"PHASE_LL_KVAR" NUMBER(10,4)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CONDUCTOR_TYPES
--------------------------------------------------------

  CREATE TABLE "GEF2012"."CONDUCTOR_TYPES" 
   (	"CONDUCTOR_NAME" VARCHAR2(50 BYTE), 
	"DIAMETER" NUMBER(10,4), 
	"GMR" NUMBER(10,4), 
	"R25" NUMBER(10,4), 
	"R50" NUMBER(10,4), 
	"NORMAL_RATING_1" NUMBER(10,4), 
	"EMERGENCY_RATING_1" NUMBER(10,4), 
	"NORMAL_RATING_2" NUMBER(10,4), 
	"EMERGENCY_RATING_2" NUMBER(10,4)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CTRL_VALUES
--------------------------------------------------------

  CREATE TABLE "GEF2012"."CTRL_VALUES" 
   (	"CTRL_VALUE_ID" VARCHAR2(35 BYTE), 
	"VALUE_TYPE" VARCHAR2(35 BYTE), 
	"ON_THRESHHOLD" NUMBER(10,4), 
	"OFF_THRESHOLD" NUMBER(10,4), 
	"DESCRIPTION" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DISTRIBUTED_LOADS
--------------------------------------------------------

  CREATE TABLE "GEF2012"."DISTRIBUTED_LOADS" 
   (	"LOAD_NAME" VARCHAR2(50 BYTE), 
	"MODEL_NAME" VARCHAR2(50 BYTE), 
	"PROFILE_NAME" VARCHAR2(50 BYTE), 
	"INTERVAL" NUMBER(*,0), 
	"PHASE" NUMBER(*,0), 
	"FROM_NODE" VARCHAR2(35 BYTE), 
	"TO_NODE" VARCHAR2(35 BYTE), 
	"RATED_VOLTAGE" NUMBER(10,4), 
	"CONNECTION" VARCHAR2(10 BYTE), 
	"KVA_RATING_A" NUMBER(10,4), 
	"KVA_RATING_B" NUMBER(10,4), 
	"KVA_RATING_C" NUMBER(10,4), 
	"POWER_FACTOR_A" NUMBER(10,4), 
	"POWER_FACTOR_B" NUMBER(10,4), 
	"POWER_FACTOR_C" NUMBER(10,4), 
	"PHASE_A_VALUE1" NUMBER(10,4), 
	"PHASE_A_VALUE2" NUMBER(10,4), 
	"PHASE_A_VALUE3" NUMBER(10,4), 
	"PHASE_B_VALUE1" NUMBER(10,4), 
	"PHASE_B_VALUE2" NUMBER(10,4), 
	"PHASE_B_VALUE3" NUMBER(10,4), 
	"PHASE_C_VALUE1" NUMBER(10,4), 
	"PHASE_C_VALUE2" NUMBER(10,4), 
	"PHASE_C_VALUE3" NUMBER(10,4), 
	"VOLTAGE_A" NUMBER(10,4), 
	"VOLTAGE_B" NUMBER(10,4), 
	"VOLTAGE_C" NUMBER(10,4), 
	"CONTROL_TYPE" VARCHAR2(35 BYTE), 
	"MEASUREMENT_TYPE" VARCHAR2(35 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LINES
--------------------------------------------------------

  CREATE TABLE "GEF2012"."LINES" 
   (	"DEVICE_NAME" VARCHAR2(50 BYTE), 
	"FROM_NODE" VARCHAR2(35 BYTE), 
	"TO_NODE" VARCHAR2(35 BYTE), 
	"LENGTH" NUMBER(10,4), 
	"CONFIG_NAME" VARCHAR2(50 BYTE), 
	"LINE_CODE_SEQIMP" VARCHAR2(50 BYTE), 
	"LINE_CODE_PHIMP" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LINES_PHASE_IMPEDANCE
--------------------------------------------------------

  CREATE TABLE "GEF2012"."LINES_PHASE_IMPEDANCE" 
   (	"LINE_CODE_PHIMP" VARCHAR2(50 BYTE), 
	"LINE_TYPE" VARCHAR2(35 BYTE), 
	"RA" NUMBER(10,4), 
	"RB" NUMBER(10,4), 
	"RC" NUMBER(10,4), 
	"XA" NUMBER(10,4), 
	"XB" NUMBER(10,4), 
	"XC" NUMBER(10,4), 
	"RN" NUMBER(10,4), 
	"XN" NUMBER(10,4), 
	"RAB" NUMBER(10,4), 
	"RBC" NUMBER(10,4), 
	"RCA" NUMBER(10,4), 
	"XAB" NUMBER(10,4), 
	"XBC" NUMBER(10,4), 
	"XCA" NUMBER(10,4), 
	"RMN" NUMBER(10,4), 
	"XMN" NUMBER(10,4), 
	"BA" NUMBER(10,4), 
	"BB" NUMBER(10,4), 
	"BC" NUMBER(10,4), 
	"BN" NUMBER(10,4), 
	"BM" NUMBER(10,4)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LINES_SEQ_IMPEDANCE
--------------------------------------------------------

  CREATE TABLE "GEF2012"."LINES_SEQ_IMPEDANCE" 
   (	"LINE_CODE_SEQIMP" VARCHAR2(50 BYTE), 
	"LINE_TYPE" VARCHAR2(35 BYTE), 
	"POSITIVE_SEQ_RESISTANCE" NUMBER(10,4), 
	"POSITIVE_SEQ_REACTANCE" NUMBER(10,4), 
	"ZERO_SEQ_RESISTANCE" NUMBER(10,4), 
	"ZERO_SEQ_REACTANCE" NUMBER(10,4), 
	"POSITIVE_SEQ_SUSCEPTANCE" NUMBER(10,4), 
	"ZERO_SEQ_SUSCEPTANCE" NUMBER(10,4), 
	"NORMAL_AMPACITY" NUMBER(*,0), 
	"EMERGENCY_AMPACITY" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LINE_CONFIGS
--------------------------------------------------------

  CREATE TABLE "GEF2012"."LINE_CONFIGS" 
   (	"CONFIG_NAME" VARCHAR2(50 BYTE), 
	"PHASE" NUMBER(*,0), 
	"PHASE_CONDUCTOR_A" VARCHAR2(35 BYTE), 
	"PHASE_CONDUCTOR_B" VARCHAR2(35 BYTE), 
	"PHASE_CONDUCTOR_C" VARCHAR2(35 BYTE), 
	"NEUTRAL_CONDUCTOR_N" VARCHAR2(35 BYTE), 
	"SPACING_NAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LOAD_MODELS
--------------------------------------------------------

  CREATE TABLE "GEF2012"."LOAD_MODELS" 
   (	"MODEL_NAME" VARCHAR2(50 BYTE), 
	"MODEL_CODE" VARCHAR2(50 BYTE), 
	"VALUE1" VARCHAR2(35 BYTE), 
	"VALUE2" VARCHAR2(35 BYTE), 
	"VALUE3" VARCHAR2(35 BYTE), 
	"DESCRIPTION" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LOAD_PROFILES
--------------------------------------------------------

  CREATE TABLE "GEF2012"."LOAD_PROFILES" 
   (	"PROFILE_NAME" VARCHAR2(50 BYTE), 
	"INTERVAL" NUMBER(*,0), 
	"DESCRIPTION" VARCHAR2(200 BYTE), 
	"SPRING_01_P" NUMBER(10,4), 
	"SPRING_01_Q" NUMBER(10,4), 
	"SPRING_02_P" NUMBER(10,4), 
	"SPRING_02_Q" NUMBER(10,4), 
	"SPRING_03_P" NUMBER(10,4), 
	"SPRING_03_Q" NUMBER(10,4), 
	"SUMMER_01_P" NUMBER(10,4), 
	"SUMMER_01_Q" NUMBER(10,4), 
	"SUMMER_02_P" NUMBER(10,4), 
	"SUMMER_02_Q" NUMBER(10,4), 
	"SUMMER_03_P" NUMBER(10,4), 
	"SUMMER_03_Q" NUMBER(10,4), 
	"FALL_01_P" NUMBER(10,4), 
	"FALL_01_Q" NUMBER(10,4), 
	"FALL_02_P" NUMBER(10,4), 
	"FALL_02_Q" NUMBER(10,4), 
	"FALL_03_P" NUMBER(10,4), 
	"FALL_03_Q" NUMBER(10,4), 
	"WINTER_01_P" NUMBER(10,4), 
	"WINTER_01_Q" NUMBER(10,4), 
	"WINTER_02_P" NUMBER(10,4), 
	"WINTER_02_Q" NUMBER(10,4), 
	"WINTER_03_P" NUMBER(10,4), 
	"WINTER_03_Q" NUMBER(10,4)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LTCS
--------------------------------------------------------

  CREATE TABLE "GEF2012"."LTCS" 
   (	"LTC_ID" VARCHAR2(50 BYTE), 
	"MIN_TAP_POSITION" NUMBER(*,0), 
	"NUMBER_OF_STEPS" NUMBER(*,0), 
	"MIN_TAP_RATIO" NUMBER(10,4), 
	"MAX_TAP_RATIO" NUMBER(10,4), 
	"STEP_SIZE" NUMBER(10,6), 
	"TAP_POSITION" NUMBER(*,0), 
	"TAP_SIDE" VARCHAR2(30 BYTE), 
	"BAND_WIDTH" NUMBER(10,4), 
	"REGULATED_BUS" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PHASES_SPACING
--------------------------------------------------------

  CREATE TABLE "GEF2012"."PHASES_SPACING" 
   (	"SPACING_NAME" VARCHAR2(50 BYTE), 
	"XA" NUMBER(10,4), 
	"HA" NUMBER(10,4), 
	"XB" NUMBER(10,4), 
	"HB" NUMBER(10,4), 
	"XC" NUMBER(10,4), 
	"HC" NUMBER(10,4), 
	"XN" NUMBER(10,4), 
	"HN" NUMBER(10,4)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PHASE_TYPES
--------------------------------------------------------

  CREATE TABLE "GEF2012"."PHASE_TYPES" 
   (	"PHASE_TYPE_ID" VARCHAR2(50 BYTE), 
	"VALUE" NUMBER(*,0), 
	"DESCRIPTION" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REGULATOR_TYPES
--------------------------------------------------------

  CREATE TABLE "GEF2012"."REGULATOR_TYPES" 
   (	"REG_TYPE_NAME" VARCHAR2(50 BYTE), 
	"DESCRIPTION" VARCHAR2(50 BYTE), 
	"CONNECTION" VARCHAR2(10 BYTE), 
	"PHASE" NUMBER(*,0), 
	"PRIMARY_CT_RATING" NUMBER(*,0), 
	"PT_RATIO" NUMBER(*,0), 
	"REGULATED_VOLTAGE_RANGE" NUMBER(10,4), 
	"STEP_SIZE" NUMBER(10,4), 
	"NUMBER_STEPS" NUMBER(*,0), 
	"BAND_WIDTH" NUMBER(10,4)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SOURCES
--------------------------------------------------------

  CREATE TABLE "GEF2012"."SOURCES" 
   (	"SOURCE_NAME" VARCHAR2(50 BYTE), 
	"FROM_NODE" VARCHAR2(35 BYTE), 
	"SUMMER_CAPACITY" NUMBER(10,4), 
	"WINTER_CAPACITY" NUMBER(10,4), 
	"NOMINAL_RATING" NUMBER(10,4), 
	"NOMINAL_VOLTAGE" NUMBER(10,4), 
	"OPERATING_VOLTAGE_MAG" NUMBER(10,4), 
	"OPERATING_VOLTAGE_ANG" NUMBER(10,4), 
	"REGULATED_VOLATGE_MAG" NUMBER(10,4), 
	"POSITIVE_SEQ_RESISTANCE" NUMBER(10,4), 
	"POSITIVE_SEQ_REACTANCE" NUMBER(10,4), 
	"ZERO_SEQ_RESISTANCE" NUMBER(10,4), 
	"ZERO_SEQ_REACTANCE" NUMBER(10,4), 
	"WDG_CONNECTION" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SPOT_LOADS
--------------------------------------------------------

  CREATE TABLE "GEF2012"."SPOT_LOADS" 
   (	"LOAD_NAME" VARCHAR2(50 BYTE), 
	"WDG2_XFMR_NAME" VARCHAR2(50 BYTE), 
	"WDG2_AUTO_XFMR_NAME" VARCHAR2(50 BYTE), 
	"MODEL_NAME" VARCHAR2(50 BYTE), 
	"PROFILE_NAME" VARCHAR2(50 BYTE), 
	"INTERVAL" NUMBER(*,0), 
	"PHASE" NUMBER(*,0), 
	"FROM_NODE" VARCHAR2(35 BYTE), 
	"RATED_VOLTAGE" NUMBER(10,4), 
	"CONNECTION" VARCHAR2(10 BYTE), 
	"KVA_RATING_A" NUMBER(10,4), 
	"KVA_RATING_B" NUMBER(10,4), 
	"KVA_RATING_C" NUMBER(10,4), 
	"USAGE_FACTOR_A" NUMBER(10,4), 
	"USAGE_FACTOR_B" NUMBER(10,4), 
	"USAGE_FACTOR_C" NUMBER(10,4), 
	"POWER_FACTOR_A" NUMBER(10,4), 
	"POWER_FACTOR_B" NUMBER(10,4), 
	"POWER_FACTOR_C" NUMBER(10,4), 
	"PHASE_A_VALUE1" NUMBER(10,4), 
	"PHASE_A_VALUE2" NUMBER(10,4), 
	"PHASE_A_VALUE3" NUMBER(10,4), 
	"PHASE_B_VALUE1" NUMBER(10,4), 
	"PHASE_B_VALUE2" NUMBER(10,4), 
	"PHASE_B_VALUE3" NUMBER(10,4), 
	"PHASE_C_VALUE1" NUMBER(10,4), 
	"PHASE_C_VALUE2" NUMBER(10,4), 
	"PHASE_C_VALUE3" NUMBER(10,4), 
	"VOLTAGE_A" NUMBER(10,4), 
	"VOLTAGE_B" NUMBER(10,4), 
	"VOLTAGE_C" NUMBER(10,4), 
	"CONTROL_TYPE" VARCHAR2(35 BYTE), 
	"MEASUREMENT_TYPE" VARCHAR2(35 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SWITCHING_DEVICES
--------------------------------------------------------

  CREATE TABLE "GEF2012"."SWITCHING_DEVICES" 
   (	"DEVICE_NAME" VARCHAR2(50 BYTE), 
	"DEVICE_TYPE_ID" VARCHAR2(50 BYTE), 
	"FROM_NODE" VARCHAR2(35 BYTE), 
	"TO_NODE" VARCHAR2(35 BYTE), 
	"NOMINAL_VOLTAGE" NUMBER(10,4), 
	"NORMAL_STATUS" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SWITCHING_DEVICE_TYPES
--------------------------------------------------------

  CREATE TABLE "GEF2012"."SWITCHING_DEVICE_TYPES" 
   (	"DEVICE_TYPE_ID" VARCHAR2(50 BYTE), 
	"NOMINAL_LIMIT" NUMBER(10,4), 
	"MAXIMUM_LIMIT" NUMBER(10,4), 
	"RATED_VOLTAGE" NUMBER(10,4)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TEST
--------------------------------------------------------

  CREATE TABLE "GEF2012"."TEST" 
   (	"ID" NUMBER(38,0), 
	"DATETIME" CHAR(38 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TRAIN
--------------------------------------------------------

  CREATE TABLE "GEF2012"."TRAIN" 
   (	"DATETIME" CHAR(38 BYTE), 
	"WP1" NUMBER(38,3), 
	"WP2" NUMBER(38,3), 
	"WP3" NUMBER(38,3), 
	"WP4" NUMBER(38,3), 
	"WP5" NUMBER(38,3), 
	"WP6" NUMBER(38,3), 
	"WP7" NUMBER(38,3)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table WDG2_AUTO_XFMRS
--------------------------------------------------------

  CREATE TABLE "GEF2012"."WDG2_AUTO_XFMRS" 
   (	"DEVICE_NAME" VARCHAR2(50 BYTE), 
	"AUTO_XFMR_TYPE_ID" VARCHAR2(50 BYTE), 
	"FROM_NODE" VARCHAR2(35 BYTE), 
	"TO_NODE" VARCHAR2(35 BYTE), 
	"PRIMARY_NOMINAL_VOLTAGE" NUMBER(10,4), 
	"SECONDARY_NOMINAL_VOLTAGE" NUMBER(10,4)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table WDG2_XFMRS
--------------------------------------------------------

  CREATE TABLE "GEF2012"."WDG2_XFMRS" 
   (	"DEVICE_NAME" VARCHAR2(50 BYTE), 
	"WDG2_TYPE_NAME" VARCHAR2(50 BYTE), 
	"FROM_NODE" VARCHAR2(35 BYTE), 
	"TO_NODE" VARCHAR2(35 BYTE), 
	"PHASE" NUMBER(*,0), 
	"PRIMARY_NOMINAL_VOLTAGE" NUMBER(10,4), 
	"SECONDARY_NOMINAL_VOLTAGE" NUMBER(10,4), 
	"PRIMARY_TAP_RATIO" NUMBER(10,4), 
	"SECONDARY_TAP_RATIO" NUMBER(10,4)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table WDG2_XFMR_TYPES
--------------------------------------------------------

  CREATE TABLE "GEF2012"."WDG2_XFMR_TYPES" 
   (	"WDG2_TYPE_NAME" VARCHAR2(50 BYTE), 
	"PHASE_TYPE_ID" VARCHAR2(50 BYTE), 
	"PHASE_SHIFT" NUMBER(10,4), 
	"RATED_KVA" NUMBER(*,0), 
	"SUMMER_CAPACITY" NUMBER(*,0), 
	"WINTER_CAPACITY" NUMBER(*,0), 
	"PRIMARY_RATED_VOLTAGE" NUMBER(10,4), 
	"SECONDARY_RATED_VOLTAGE" NUMBER(10,4), 
	"POSITIVE_SEQ_RESISTANCE" NUMBER(10,4), 
	"POSITIVE_SEQ_REACTANCE" NUMBER(10,4), 
	"POSITIVE_SEQ_IMPEDANCE_PERCENT" NUMBER(10,4), 
	"POSITIVE_SEQ_XR_RATIO" NUMBER(10,4), 
	"ZERO_SEQ_RESISTANCE" NUMBER(10,4), 
	"ZERO_SEQ_REACTANCE" NUMBER(10,4), 
	"ZERO_SEQ_IMPEDANCE_PERCENT" NUMBER(10,4), 
	"ZERO_SEQ_XR_RATIO" NUMBER(10,4), 
	"PRIMARY_GND_RESISTANCE" NUMBER(10,4), 
	"PRIMARY_GND_REACTANCE" NUMBER(10,4), 
	"SECONDARY_GND_RESISTANCE" NUMBER(10,4), 
	"SECONDARY_GND_REACTANCE" NUMBER(10,4), 
	"NOLOAD_LOSS" NUMBER(10,4), 
	"MAG_POWER_FACTOR" NUMBER(10,4), 
	"WDG2_CONFIG_ID" VARCHAR2(50 BYTE), 
	"LTC_ID" VARCHAR2(50 BYTE), 
	"REGULATOR_ID" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table WF_1
--------------------------------------------------------

  CREATE TABLE "GEF2012"."WF_1" 
   (	"DATETIME" CHAR(38 BYTE), 
	"HORS" NUMBER(38,0), 
	"U" NUMBER(38,2), 
	"V" NUMBER(38,2), 
	"WS" NUMBER(38,2), 
	"WD" NUMBER(38,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table LINE_CONFIGS
--------------------------------------------------------

  ALTER TABLE "GEF2012"."LINE_CONFIGS" ADD CONSTRAINT "UQ_LINE_CONFIGS_CONFIG_NAME" UNIQUE ("CONFIG_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GEF2012"."LINE_CONFIGS" MODIFY ("PHASE" NOT NULL ENABLE);
  ALTER TABLE "GEF2012"."LINE_CONFIGS" MODIFY ("CONFIG_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table WDG2_XFMRS
--------------------------------------------------------

  ALTER TABLE "GEF2012"."WDG2_XFMRS" ADD CONSTRAINT "UQ_WDG2_XFMRS_DEVICE_NAME" UNIQUE ("DEVICE_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GEF2012"."WDG2_XFMRS" MODIFY ("SECONDARY_NOMINAL_VOLTAGE" NOT NULL ENABLE);
  ALTER TABLE "GEF2012"."WDG2_XFMRS" MODIFY ("PRIMARY_NOMINAL_VOLTAGE" NOT NULL ENABLE);
  ALTER TABLE "GEF2012"."WDG2_XFMRS" MODIFY ("TO_NODE" NOT NULL ENABLE);
  ALTER TABLE "GEF2012"."WDG2_XFMRS" MODIFY ("FROM_NODE" NOT NULL ENABLE);
  ALTER TABLE "GEF2012"."WDG2_XFMRS" MODIFY ("WDG2_TYPE_NAME" NOT NULL ENABLE);
  ALTER TABLE "GEF2012"."WDG2_XFMRS" MODIFY ("DEVICE_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CABLES_SPACING
--------------------------------------------------------

  ALTER TABLE "GEF2012"."CABLES_SPACING" ADD CONSTRAINT "UQ_CABLES_SPACING_SPACING_ID" UNIQUE ("SPACING_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GEF2012"."CABLES_SPACING" MODIFY ("SPACING_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table WDG2_XFMR_TYPES
--------------------------------------------------------

  ALTER TABLE "GEF2012"."WDG2_XFMR_TYPES" ADD CONSTRAINT "PK_WDG2_XFMR_TYPES" PRIMARY KEY ("WDG2_TYPE_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GEF2012"."WDG2_XFMR_TYPES" MODIFY ("WDG2_CONFIG_ID" NOT NULL ENABLE);
  ALTER TABLE "GEF2012"."WDG2_XFMR_TYPES" MODIFY ("SECONDARY_RATED_VOLTAGE" NOT NULL ENABLE);
  ALTER TABLE "GEF2012"."WDG2_XFMR_TYPES" MODIFY ("PRIMARY_RATED_VOLTAGE" NOT NULL ENABLE);
  ALTER TABLE "GEF2012"."WDG2_XFMR_TYPES" MODIFY ("WINTER_CAPACITY" NOT NULL ENABLE);
  ALTER TABLE "GEF2012"."WDG2_XFMR_TYPES" MODIFY ("SUMMER_CAPACITY" NOT NULL ENABLE);
  ALTER TABLE "GEF2012"."WDG2_XFMR_TYPES" MODIFY ("RATED_KVA" NOT NULL ENABLE);
  ALTER TABLE "GEF2012"."WDG2_XFMR_TYPES" MODIFY ("PHASE_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "GEF2012"."WDG2_XFMR_TYPES" MODIFY ("WDG2_TYPE_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CABLE_TYPES
--------------------------------------------------------

  ALTER TABLE "GEF2012"."CABLE_TYPES" ADD CONSTRAINT "UQ_CABLE_TYPES_WIRE_NAME" UNIQUE ("CABLE_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GEF2012"."CABLE_TYPES" MODIFY ("PHASE_CONDUCTOR_NAME" NOT NULL ENABLE);
  ALTER TABLE "GEF2012"."CABLE_TYPES" MODIFY ("CABLE_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CTRL_VALUES
--------------------------------------------------------

  ALTER TABLE "GEF2012"."CTRL_VALUES" ADD CONSTRAINT "UQ_CTRL_VALUES_CTRL_VALUE_ID" UNIQUE ("CTRL_VALUE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GEF2012"."CTRL_VALUES" MODIFY ("OFF_THRESHOLD" NOT NULL ENABLE);
  ALTER TABLE "GEF2012"."CTRL_VALUES" MODIFY ("ON_THRESHHOLD" NOT NULL ENABLE);
  ALTER TABLE "GEF2012"."CTRL_VALUES" MODIFY ("CTRL_VALUE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DISTRIBUTED_LOADS
--------------------------------------------------------

  ALTER TABLE "GEF2012"."DISTRIBUTED_LOADS" ADD CONSTRAINT "UQ_DISTRIBUTED_LOADS_LOAD_NAME" UNIQUE ("LOAD_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GEF2012"."DISTRIBUTED_LOADS" MODIFY ("CONNECTION" NOT NULL ENABLE);
  ALTER TABLE "GEF2012"."DISTRIBUTED_LOADS" MODIFY ("RATED_VOLTAGE" NOT NULL ENABLE);
  ALTER TABLE "GEF2012"."DISTRIBUTED_LOADS" MODIFY ("FROM_NODE" NOT NULL ENABLE);
  ALTER TABLE "GEF2012"."DISTRIBUTED_LOADS" MODIFY ("PHASE" NOT NULL ENABLE);
  ALTER TABLE "GEF2012"."DISTRIBUTED_LOADS" MODIFY ("MODEL_NAME" NOT NULL ENABLE);
  ALTER TABLE "GEF2012"."DISTRIBUTED_LOADS" MODIFY ("LOAD_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LINES_PHASE_IMPEDANCE
--------------------------------------------------------

  ALTER TABLE "GEF2012"."LINES_PHASE_IMPEDANCE" ADD CONSTRAINT "PK_LINES_PHASE_IMPEDANCE" PRIMARY KEY ("LINE_CODE_PHIMP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GEF2012"."LINES_PHASE_IMPEDANCE" MODIFY ("LINE_CODE_PHIMP" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SOURCES
--------------------------------------------------------

  ALTER TABLE "GEF2012"."SOURCES" ADD CONSTRAINT "UQ_SOURCES_SOURCE_NAME" UNIQUE ("SOURCE_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GEF2012"."SOURCES" MODIFY ("REGULATED_VOLATGE_MAG" NOT NULL ENABLE);
  ALTER TABLE "GEF2012"."SOURCES" MODIFY ("OPERATING_VOLTAGE_MAG" NOT NULL ENABLE);
  ALTER TABLE "GEF2012"."SOURCES" MODIFY ("NOMINAL_VOLTAGE" NOT NULL ENABLE);
  ALTER TABLE "GEF2012"."SOURCES" MODIFY ("NOMINAL_RATING" NOT NULL ENABLE);
  ALTER TABLE "GEF2012"."SOURCES" MODIFY ("WINTER_CAPACITY" NOT NULL ENABLE);
  ALTER TABLE "GEF2012"."SOURCES" MODIFY ("SUMMER_CAPACITY" NOT NULL ENABLE);
  ALTER TABLE "GEF2012"."SOURCES" MODIFY ("FROM_NODE" NOT NULL ENABLE);
  ALTER TABLE "GEF2012"."SOURCES" MODIFY ("SOURCE_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BUS_COORDS
--------------------------------------------------------

  ALTER TABLE "GEF2012"."BUS_COORDS" ADD CONSTRAINT "UQ_BUS_COORDS_NODE_NAME" UNIQUE ("NODE_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GEF2012"."BUS_COORDS" MODIFY ("Y_COORD" NOT NULL ENABLE);
  ALTER TABLE "GEF2012"."BUS_COORDS" MODIFY ("X_COORD" NOT NULL ENABLE);
  ALTER TABLE "GEF2012"."BUS_COORDS" MODIFY ("NODE_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PHASE_TYPES
--------------------------------------------------------

  ALTER TABLE "GEF2012"."PHASE_TYPES" ADD CONSTRAINT "UQ_PHASE_TYPES_PHASE_TYPE_ID" UNIQUE ("PHASE_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GEF2012"."PHASE_TYPES" MODIFY ("VALUE" NOT NULL ENABLE);
  ALTER TABLE "GEF2012"."PHASE_TYPES" MODIFY ("PHASE_TYPE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LTCS
--------------------------------------------------------

  ALTER TABLE "GEF2012"."LTCS" ADD CONSTRAINT "UQ_LTCS_LLTC_ID" UNIQUE ("LTC_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GEF2012"."LTCS" MODIFY ("LTC_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CABLE_CONFIGS
--------------------------------------------------------

  ALTER TABLE "GEF2012"."CABLE_CONFIGS" ADD CONSTRAINT "UQ_CABLE_CONFIGS_CONFIG_NAME" UNIQUE ("CONFIG_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GEF2012"."CABLE_CONFIGS" MODIFY ("PHASE" NOT NULL ENABLE);
  ALTER TABLE "GEF2012"."CABLE_CONFIGS" MODIFY ("CONFIG_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PHASES_SPACING
--------------------------------------------------------

  ALTER TABLE "GEF2012"."PHASES_SPACING" ADD CONSTRAINT "UQ_PHASES_SPACING_SPACING_NAME" UNIQUE ("SPACING_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GEF2012"."PHASES_SPACING" MODIFY ("SPACING_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CABLES
--------------------------------------------------------

  ALTER TABLE "GEF2012"."CABLES" ADD CONSTRAINT "UQ_CABLES_DEVICE_NAME" UNIQUE ("DEVICE_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GEF2012"."CABLES" MODIFY ("LENGTH" NOT NULL ENABLE);
  ALTER TABLE "GEF2012"."CABLES" MODIFY ("TO_NODE" NOT NULL ENABLE);
  ALTER TABLE "GEF2012"."CABLES" MODIFY ("FROM_NODE" NOT NULL ENABLE);
  ALTER TABLE "GEF2012"."CABLES" MODIFY ("DEVICE_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CABLES_PHASE_IMPEDANCE
--------------------------------------------------------

  ALTER TABLE "GEF2012"."CABLES_PHASE_IMPEDANCE" ADD CONSTRAINT "PK_CABLES_PHASE_IMPEDANCE" PRIMARY KEY ("CABLE_CODE_PHIMP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GEF2012"."CABLES_PHASE_IMPEDANCE" MODIFY ("CABLE_CODE_PHIMP" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table WDG2_AUTO_XFMRS
--------------------------------------------------------

  ALTER TABLE "GEF2012"."WDG2_AUTO_XFMRS" ADD CONSTRAINT "UQ_WDG2_AUTO_XFMRS_DEVICE_NAME" UNIQUE ("DEVICE_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GEF2012"."WDG2_AUTO_XFMRS" MODIFY ("DEVICE_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CABLES_SEQ_IMPEDANCE
--------------------------------------------------------

  ALTER TABLE "GEF2012"."CABLES_SEQ_IMPEDANCE" ADD CONSTRAINT "PK_CABLES_SEQ_IMPEDANCE" PRIMARY KEY ("CABLE_CODE_SEQIMP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GEF2012"."CABLES_SEQ_IMPEDANCE" MODIFY ("CABLE_CODE_SEQIMP" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LINES_SEQ_IMPEDANCE
--------------------------------------------------------

  ALTER TABLE "GEF2012"."LINES_SEQ_IMPEDANCE" ADD CONSTRAINT "PK_LINES_SEQ_IMPEDANCE" PRIMARY KEY ("LINE_CODE_SEQIMP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GEF2012"."LINES_SEQ_IMPEDANCE" MODIFY ("LINE_CODE_SEQIMP" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CENTER_TAPPED_LOADS
--------------------------------------------------------

  ALTER TABLE "GEF2012"."CENTER_TAPPED_LOADS" ADD CONSTRAINT "PK_CENTER_TAPPED_LOADS" PRIMARY KEY ("LOAD_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GEF2012"."CENTER_TAPPED_LOADS" MODIFY ("CONNECTION" NOT NULL ENABLE);
  ALTER TABLE "GEF2012"."CENTER_TAPPED_LOADS" MODIFY ("RATED_VOLTAGE" NOT NULL ENABLE);
  ALTER TABLE "GEF2012"."CENTER_TAPPED_LOADS" MODIFY ("FROM_NODE" NOT NULL ENABLE);
  ALTER TABLE "GEF2012"."CENTER_TAPPED_LOADS" MODIFY ("PHASE" NOT NULL ENABLE);
  ALTER TABLE "GEF2012"."CENTER_TAPPED_LOADS" MODIFY ("MODEL_NAME" NOT NULL ENABLE);
  ALTER TABLE "GEF2012"."CENTER_TAPPED_LOADS" MODIFY ("LOAD_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LOAD_PROFILES
--------------------------------------------------------

  ALTER TABLE "GEF2012"."LOAD_PROFILES" ADD CONSTRAINT "PK_LOAD_PROFILES" PRIMARY KEY ("PROFILE_NAME", "INTERVAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GEF2012"."LOAD_PROFILES" MODIFY ("INTERVAL" NOT NULL ENABLE);
  ALTER TABLE "GEF2012"."LOAD_PROFILES" MODIFY ("PROFILE_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LOAD_MODELS
--------------------------------------------------------

  ALTER TABLE "GEF2012"."LOAD_MODELS" ADD CONSTRAINT "UQ_LOAD_MODELS_MODEL_NAME" UNIQUE ("MODEL_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GEF2012"."LOAD_MODELS" MODIFY ("MODEL_CODE" NOT NULL ENABLE);
  ALTER TABLE "GEF2012"."LOAD_MODELS" MODIFY ("MODEL_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LINES
--------------------------------------------------------

  ALTER TABLE "GEF2012"."LINES" ADD CONSTRAINT "UQ_LINES_DEVICE_NAME" UNIQUE ("DEVICE_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GEF2012"."LINES" MODIFY ("LENGTH" NOT NULL ENABLE);
  ALTER TABLE "GEF2012"."LINES" MODIFY ("TO_NODE" NOT NULL ENABLE);
  ALTER TABLE "GEF2012"."LINES" MODIFY ("FROM_NODE" NOT NULL ENABLE);
  ALTER TABLE "GEF2012"."LINES" MODIFY ("DEVICE_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CONDUCTOR_TYPES
--------------------------------------------------------

  ALTER TABLE "GEF2012"."CONDUCTOR_TYPES" ADD CONSTRAINT "PK_CONDUCTOR_TYPES" PRIMARY KEY ("CONDUCTOR_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GEF2012"."CONDUCTOR_TYPES" MODIFY ("CONDUCTOR_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SWITCHING_DEVICE_TYPES
--------------------------------------------------------

  ALTER TABLE "GEF2012"."SWITCHING_DEVICE_TYPES" ADD CONSTRAINT "PK_SWITCHING_DEVICE_TYPES" PRIMARY KEY ("DEVICE_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GEF2012"."SWITCHING_DEVICE_TYPES" MODIFY ("RATED_VOLTAGE" NOT NULL ENABLE);
  ALTER TABLE "GEF2012"."SWITCHING_DEVICE_TYPES" MODIFY ("MAXIMUM_LIMIT" NOT NULL ENABLE);
  ALTER TABLE "GEF2012"."SWITCHING_DEVICE_TYPES" MODIFY ("NOMINAL_LIMIT" NOT NULL ENABLE);
  ALTER TABLE "GEF2012"."SWITCHING_DEVICE_TYPES" MODIFY ("DEVICE_TYPE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SWITCHING_DEVICES
--------------------------------------------------------

  ALTER TABLE "GEF2012"."SWITCHING_DEVICES" ADD CONSTRAINT "PK_SWITCHING_DEVICES" PRIMARY KEY ("DEVICE_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GEF2012"."SWITCHING_DEVICES" MODIFY ("NORMAL_STATUS" NOT NULL ENABLE);
  ALTER TABLE "GEF2012"."SWITCHING_DEVICES" MODIFY ("NOMINAL_VOLTAGE" NOT NULL ENABLE);
  ALTER TABLE "GEF2012"."SWITCHING_DEVICES" MODIFY ("TO_NODE" NOT NULL ENABLE);
  ALTER TABLE "GEF2012"."SWITCHING_DEVICES" MODIFY ("FROM_NODE" NOT NULL ENABLE);
  ALTER TABLE "GEF2012"."SWITCHING_DEVICES" MODIFY ("DEVICE_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "GEF2012"."SWITCHING_DEVICES" MODIFY ("DEVICE_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SPOT_LOADS
--------------------------------------------------------

  ALTER TABLE "GEF2012"."SPOT_LOADS" ADD CONSTRAINT "UQ_SPOT_LOADS_LOAD_NAME" UNIQUE ("LOAD_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GEF2012"."SPOT_LOADS" MODIFY ("CONNECTION" NOT NULL ENABLE);
  ALTER TABLE "GEF2012"."SPOT_LOADS" MODIFY ("RATED_VOLTAGE" NOT NULL ENABLE);
  ALTER TABLE "GEF2012"."SPOT_LOADS" MODIFY ("FROM_NODE" NOT NULL ENABLE);
  ALTER TABLE "GEF2012"."SPOT_LOADS" MODIFY ("PHASE" NOT NULL ENABLE);
  ALTER TABLE "GEF2012"."SPOT_LOADS" MODIFY ("MODEL_NAME" NOT NULL ENABLE);
  ALTER TABLE "GEF2012"."SPOT_LOADS" MODIFY ("LOAD_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REGULATOR_TYPES
--------------------------------------------------------

  ALTER TABLE "GEF2012"."REGULATOR_TYPES" ADD CONSTRAINT "PK_REGULATOR_TYPES" PRIMARY KEY ("REG_TYPE_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GEF2012"."REGULATOR_TYPES" MODIFY ("REG_TYPE_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CABLES
--------------------------------------------------------

  ALTER TABLE "GEF2012"."CABLES" ADD CONSTRAINT "FK_CABLES_CABLE_CONFIGS" FOREIGN KEY ("CONFIG_NAME")
	  REFERENCES "GEF2012"."CABLE_CONFIGS" ("CONFIG_NAME") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CABLE_TYPES
--------------------------------------------------------

  ALTER TABLE "GEF2012"."CABLE_TYPES" ADD CONSTRAINT "FK_CABLE_TYPES_CONDUCTOR_TYPES" FOREIGN KEY ("PHASE_CONDUCTOR_NAME")
	  REFERENCES "GEF2012"."CONDUCTOR_TYPES" ("CONDUCTOR_NAME") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LINES
--------------------------------------------------------

  ALTER TABLE "GEF2012"."LINES" ADD CONSTRAINT "FK_LINES_BUS_COORDS" FOREIGN KEY ("FROM_NODE")
	  REFERENCES "GEF2012"."BUS_COORDS" ("NODE_NAME") ENABLE;
  ALTER TABLE "GEF2012"."LINES" ADD CONSTRAINT "FK_LINES_BUS_COORDS_02" FOREIGN KEY ("TO_NODE")
	  REFERENCES "GEF2012"."BUS_COORDS" ("NODE_NAME") ENABLE;
  ALTER TABLE "GEF2012"."LINES" ADD CONSTRAINT "FK_LINES_LINES_PHASE_IMPEDANCE" FOREIGN KEY ("LINE_CODE_PHIMP")
	  REFERENCES "GEF2012"."LINES_PHASE_IMPEDANCE" ("LINE_CODE_PHIMP") ENABLE;
  ALTER TABLE "GEF2012"."LINES" ADD CONSTRAINT "FK_LINES_LINES_SEQ_IMPEDANCE" FOREIGN KEY ("LINE_CODE_SEQIMP")
	  REFERENCES "GEF2012"."LINES_SEQ_IMPEDANCE" ("LINE_CODE_SEQIMP") ENABLE;
  ALTER TABLE "GEF2012"."LINES" ADD CONSTRAINT "FK_LINES_LINE_CONFIGS" FOREIGN KEY ("CONFIG_NAME")
	  REFERENCES "GEF2012"."LINE_CONFIGS" ("CONFIG_NAME") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LINE_CONFIGS
--------------------------------------------------------

  ALTER TABLE "GEF2012"."LINE_CONFIGS" ADD CONSTRAINT "FK_LINE_CONFIGS_PHASES_SPACING" FOREIGN KEY ("SPACING_NAME")
	  REFERENCES "GEF2012"."PHASES_SPACING" ("SPACING_NAME") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SOURCES
--------------------------------------------------------

  ALTER TABLE "GEF2012"."SOURCES" ADD CONSTRAINT "FK_SOURCES_BUS_COORDS" FOREIGN KEY ("FROM_NODE")
	  REFERENCES "GEF2012"."BUS_COORDS" ("NODE_NAME") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SPOT_LOADS
--------------------------------------------------------

  ALTER TABLE "GEF2012"."SPOT_LOADS" ADD CONSTRAINT "FK_SPOT_LOADS_BUS_COORDS" FOREIGN KEY ("FROM_NODE")
	  REFERENCES "GEF2012"."BUS_COORDS" ("NODE_NAME") ENABLE;
  ALTER TABLE "GEF2012"."SPOT_LOADS" ADD CONSTRAINT "FK_SPOT_LOADS_WDG2_XFMRS" FOREIGN KEY ("WDG2_XFMR_NAME")
	  REFERENCES "GEF2012"."WDG2_XFMRS" ("DEVICE_NAME") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table WDG2_AUTO_XFMRS
--------------------------------------------------------

  ALTER TABLE "GEF2012"."WDG2_AUTO_XFMRS" ADD CONSTRAINT "FK_WDG2_AUTO_XFMRS_BUS_COORDS" FOREIGN KEY ("FROM_NODE")
	  REFERENCES "GEF2012"."BUS_COORDS" ("NODE_NAME") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table WDG2_XFMRS
--------------------------------------------------------

  ALTER TABLE "GEF2012"."WDG2_XFMRS" ADD CONSTRAINT "FK_WDG2_XFMRS_BUS_COORDS" FOREIGN KEY ("FROM_NODE")
	  REFERENCES "GEF2012"."BUS_COORDS" ("NODE_NAME") ENABLE;
  ALTER TABLE "GEF2012"."WDG2_XFMRS" ADD CONSTRAINT "FK_WDG2_XFMRS_BUS_COORDS_02" FOREIGN KEY ("TO_NODE")
	  REFERENCES "GEF2012"."BUS_COORDS" ("NODE_NAME") ENABLE;
  ALTER TABLE "GEF2012"."WDG2_XFMRS" ADD CONSTRAINT "FK_WDG2_XFMRS_WDG2_XFMR_TYPES" FOREIGN KEY ("WDG2_TYPE_NAME")
	  REFERENCES "GEF2012"."WDG2_XFMR_TYPES" ("WDG2_TYPE_NAME") ENABLE;
